### ISSUE TITLE
Build cherrypi get error

### ISSUE THREAD

**Issue by SeevenYoung** [TorchCraft/TorchCraftAI#11]
I got this error when I input this cmd
`msbuild CherryPi.sln  /property:Configuration=Release /m
`

>    “E:\git\github\TorchCraftAI\build\CherryPi.sln”(默认目标) (1) ->
       “E:\git\github\TorchCraftAI\build\common\common.vcxproj.metaproj”(默认目标) (6) ->
       “E:\git\github\TorchCraftAI\build\common\common.vcxproj”(默认目标) (20) ->
       (ClCompile 目标) ->
         E:\git\github\TorchCraftAI\3rdparty\include\autogradpp/autograd.h(106): error C3668: “ag::Sequential::clone”: 包含重写说明符“override”的方法没有重写任何基类方法 (编译源文件 E:\git\github\TorchCraftAI\common\autograd\operations.cpp) [E:\git\github\TorchCraftAI\build\common\common.vcxpro
       j]
         E:\git\github\TorchCraftAI\3rdparty\include\autogradpp/autograd.h(106): error C3668: “ag::Sequential::clone”: 包含重写说明符“override”的方法没有重写任何基类方法 (编译源文件 E:\git\github\TorchCraftAI\common\autograd\distributions.cpp) [E:\git\github\TorchCraftAI\build\common\common.vcx
       proj]
         E:\git\github\TorchCraftAI\3rdparty\include\autogradpp/autograd.h(106): error C3668: “ag::Sequential::clone”: 包含重写说明符“override”的方法没有重写任何基类方法 (编译源文件 E:\git\github\TorchCraftAI\common\autograd\utils.cpp) [E:\git\github\TorchCraftAI\build\common\common.vcxproj]
         E:\git\github\TorchCraftAI\3rdparty\include\autogradpp/autograd.h(106): error C3668: “ag::Sequential::clone”: 包含重写说明符“override”的方法没有重写任何基类方法 (编译源文件 E:\git\github\TorchCraftAI\common\autograd\debug.cpp) [E:\git\github\TorchCraftAI\build\common\common.vcxproj]
         E:\git\github\TorchCraftAI\3rdparty\include\autogradpp/autograd.h(106): error C3668: “ag::Sequential::clone”: 包含重写说明符“override”的方法没有重写任何基类方法 (编译源文件 E:\git\github\TorchCraftAI\common\autograd\models.cpp) [E:\git\github\TorchCraftAI\build\common\common.vcxproj]
         E:\git\github\TorchCraftAI\3rdparty\include\autogradpp/autograd.h(106): error C3668: “ag::Sequential::clone”: 包含重写说明符“override”的方法没有重写任何基类方法 (编译源文件 E:\git\github\TorchCraftAI\common\rand.cpp) [E:\git\github\TorchCraftAI\build\common\common.vcxproj]

**Comment by ianchen28** [comment]
Same problem.
Personally, the problem seems to be the version mismatch of `autogradpp` and `pytorch`.
the function

https://github.com/TorchCraft/TorchCraftAI/blob/39bc82495a6ae2576564adbdf99b3d6d6254e85a/3rdparty/include/autogradpp/autograd.h#L106-L107
overrides the latest pytorch function

https://github.com/pytorch/pytorch/blob/f1c8e01524067f6eb0976ade32139e591b907f24/torch/csrc/api/include/torch/nn/cloneable.h#L34

however the TorchCraftAI project did not pull the latest version of pytorch.
@ebetica would you please have a look?

**Comment by SeevenYoung** [comment]
> Same problem.
> Personally, the problem seems to be the version mismatch of `autogradpp` and `pytorch`.
> the function
> 
> [TorchCraftAI/3rdparty/include/autogradpp/autograd.h](https://github.com/TorchCraft/TorchCraftAI/blob/39bc82495a6ae2576564adbdf99b3d6d6254e85a/3rdparty/include/autogradpp/autograd.h#L106-L107)
> 
> Lines 106 to 107 in [39bc824](/TorchCraft/TorchCraftAI/commit/39bc82495a6ae2576564adbdf99b3d6d6254e85a)
> 
>  std::shared_ptr<torch::nn::Module> clone( 
>      at::optional<at::Device> const& = c10::nullopt) const override; 
> 
> overrides the latest pytorch function
> https://github.com/pytorch/pytorch/blob/f1c8e01524067f6eb0976ade32139e591b907f24/torch/csrc/api/include/torch/nn/cloneable.h#L34
> 
> however the TorchCraftAI project did not pull the latest version of pytorch.
> @ebetica would you please have a look?

you mean just pull the latest pytorch would be fine?

**Comment by ianchen28** [comment]
I'm not sure.  Cuz I am currently playing on the previous version (commit f67963b6e93549e381e110fe2ec285cfac667933) which is verified. Just to walk around this problem at this time : P

**Comment by SeevenYoung** [comment]
> I'm not sure. Cuz I am currently playing on the previous version (commit [f67963b](https://github.com/TorchCraft/TorchCraftAI/commit/f67963b6e93549e381e110fe2ec285cfac667933)) which is verified. Just to walk around this problem at this time : P

thanks, it works!

**Comment by leonfg** [comment]
> 
> 
> > I'm not sure. Cuz I am currently playing on the previous version (commit [f67963b](https://github.com/TorchCraft/TorchCraftAI/commit/f67963b6e93549e381e110fe2ec285cfac667933)) which is verified. Just to walk around this problem at this time : P
> 
> thanks, it works!

请问具体是怎么操作的？我将最新pytorch合入后报了新的问题：

> D:\Work\TorchCraftAI\3rdparty\cereal\include\cereal/access.hpp(314): error C2248: “torch::optim::Adam::Adam”: 无法访问 private 成员(在“torch::optim::Adam”类中声明) (编译源文件 D:\Work\TorchCraftAI\common\rand.cpp) [D:\Work\TorchCraftAI\build\common\common.vcxproj]

类似上面这样的

**Comment by SeevenYoung** [comment]
> 请问具体是怎么操作的？我将最新pytorch合入后报了新的问题：
> 
> >

直接将版本reset到 f67963b，再按照文档全部重来一遍

**Comment by leonfg** [comment]
> 
> 
> > 请问具体是怎么操作的？我将最新pytorch合入后报了新的问题：
> > >
> 
> 直接将版本reset到 [f67963b](https://github.com/TorchCraft/TorchCraftAI/commit/f67963b6e93549e381e110fe2ec285cfac667933)，再按照文档全部重来一遍

ok， 我以为works是指的合入新pytorch，679那个版本我这也没问题。谢谢

**Comment by jgehring** [comment]
This seems resolved? Feel free to re-open if this is still an issue.
