### ISSUE TITLE
build cherrypi on windows: cmake error

### ISSUE THREAD

**Issue by leonfg** [TorchCraft/TorchCraftAI#12]
I built pytorch, gflags, glog and zmq successfully under commit [65f345b](https://github.com/TorchCraft/TorchCraftAI/tree/65f345b70662e8236fcb40201040c3c99f401df6). In the build cherrypi procedure, command "cmake .. -DMSVC=true -DZMQ_LIBRARY="../3rdparty/zmq.lib" -DZMQ_INCLUDE_DIR="../3rdparty/libzmq/include" -DGFLAGS_LIBRARY="../3rdparty/gflags_static.lib" -DGFLAGS_INCLUDE_DIR="../3rdparty/gflags/build/include" -DGLOG_ROOT_DIR="../3rdparty/glog" -DCMAKE_CXX_FLAGS_RELEASE="/MP /EHsc" -G "Visual Studio 15 2017 Win64"" failed:
```bash
-- ZSTD_LEGACY_SUPPORT not defined!
ZSTD VERSION 1.3.2
-- Could NOT find GFLAGS (missing: GFLAGS_LIBRARY)
CMake Warning at CMakeLists.txt:81 (FIND_PACKAGE):
  Found package configuration file:

    D:/Work/TorchCraftAI/3rdparty/glog/build/glog-config.cmake

  but it set glog_FOUND to FALSE so package "glog" is considered to be NOT
  FOUND.  Reason given by package:

  glog could not be found because dependency gflags could not be found.



-- CMake version: 3.14.0
-- Version: 5.0.0
-- Build type: Release
-- CPP14_FLAG:
-- Could NOT find GFLAGS (missing: GFLAGS_LIBRARY)
-- Could NOT find libdw (missing: LIBDW_LIBRARY LIBDW_INCLUDE_DIR)
-- Could NOT find libbfd (missing: LIBBFD_LIBRARY LIBBFD_INCLUDE_DIR LIBDL_LIBRARY LIBDL_INCLUDE_DIR)
-- BACKWARD_HAS_UNWIND=1
-- BACKWARD_HAS_BACKTRACE=0
-- BACKWARD_HAS_BACKTRACE_SYMBOL=1
-- BACKWARD_HAS_DW=0
-- BACKWARD_HAS_BFD=0
-- Could NOT find Backward (missing: BACKWARD_LIBRARIES)
-- Could NOT find GFLAGS (missing: GFLAGS_LIBRARY)
-- cotire 1.7.10 loaded.
-- Could NOT find libdw (missing: LIBDW_LIBRARY LIBDW_INCLUDE_DIR)
-- Could NOT find libbfd (missing: LIBBFD_LIBRARY LIBBFD_INCLUDE_DIR LIBDL_LIBRARY LIBDL_INCLUDE_DIR)
-- BACKWARD_HAS_UNWIND=1
-- BACKWARD_HAS_BACKTRACE=0
-- BACKWARD_HAS_BACKTRACE_SYMBOL=1
-- BACKWARD_HAS_DW=0
-- BACKWARD_HAS_BFD=0
-- Could NOT find Backward (missing: BACKWARD_LIBRARIES)
-- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LIB_glog
    linked by target "common" in directory D:/Work/TorchCraftAI2/common
    linked by target "cherrypi" in directory D:/Work/TorchCraftAI2/src

-- Configuring incomplete, errors occurred!
See also "D:/Work/TorchCraftAI2/build/CMakeFiles/CMakeOutput.log".
See also "D:/Work/TorchCraftAI2/build/CMakeFiles/CMakeError.log".
```

CMakeOutput.log: https://paste.ubuntu.com/p/y7vVS8zpPd/
CMakeError.log: https://paste.ubuntu.com/p/9VTDykgKyp/

**Comment by Qiyangcao** [comment]
Same Problem, did you solve it?

**Comment by leonfg** [comment]
> 
> 
> Same Problem, did you solve it?

Not yet. f67963b is OK.

**Comment by JarvisLee0423** [comment]
Did you get the solution now? I am trouble in the same problem....

**Comment by JarvisLee0423** [comment]
@Qiyangcao Have you solved this question? I met the same problem, but I get no idea about how to handle with this......

**Comment by JarvisLee0423** [comment]
@leonfg Hello?Have you getten some idea about this?

**Comment by Qiyangcao** [comment]
@JarvisLee0423 

Hi, my friend helped me to handle this problem , but it's quite complicated, and I didn't solve it myself, so I  missed many details....  leonfg mentioned another version is fine, but I didn't try that. I remember the compiling error occurs in the file of /TorchCraftAI/src/gameutils/mapmatcher.cpp after successfully compiling the pytorch library ,glog and gflags

**This is the part of file how my friends modified to:**
const std::vector<std::pair<std::regex, std::string>> kReplacements = {
{std::regex(""), "fightingspirit"},
{std::regex("[z]*"), "empireofthesun"},
{std::regex("[z]*"), "heartbreakridge"},
{std::regex("[z]*"), "sniperridge"},
{std::regex("colosseumii"), "colosseum"},
{std::regex("circuitbreakers"), "circuitbreaker"},
{std::regex(""), "bloodyridge"}};

But  I am not sure whether it works, the cmake error is always annoying, especially this error is not wrote by yourself and it's quite a long time ....

**Comment by JarvisLee0423** [comment]
@Qiyangcao Thanks, I will try it first, and could you tell me about the other solution about this problem which was mentioned by leonfg. I am afriad of that I can not solve this problem by following this solution.

**Comment by Qiyangcao** [comment]
> @Qiyangcao Thanks, I will try it first, and could you tell me about the other solution about this problem which was mentioned by leonfg. I am afriad of that I can not solve this problem by following this solution.

Actually you can view his reply ,which means you should call **git checkout f67963b** to turn to this branch from the master one, but I am not really sure whether it works

> > Same Problem, did you solve it?
> 
> Not yet. [f67963b](https://github.com/TorchCraft/TorchCraftAI/commit/f67963b6e93549e381e110fe2ec285cfac667933) is OK.

**Comment by Qiyangcao** [comment]
@JarvisLee0423 
Actually you can view his reply ,which means you should call **git checkout f67963b** to turn to this branch from the master one, but I am not really sure whether it works

> > Same Problem, did you solve it?
> 
> Not yet. [f67963b](https://github.com/TorchCraft/TorchCraftAI/commit/f67963b6e93549e381e110fe2ec285cfac667933) is OK.

**Comment by JarvisLee0423** [comment]
@Qiyangcao I have already checked out this link, however, it just showed me that the developer deleted some files, and I have also checked the directory about these files which were deleted, these files not exists in my pytorch directory...

**Comment by Qiyangcao** [comment]
@JarvisLee0423 if you check out this link , you should build pytorch gflags and glog after checkout, rather than building them in the master version.

**Comment by JarvisLee0423** [comment]
@Qiyangcao What's your mean of building in checkout? And I have already checked your first solution, there are some weird korea words, therefore, should I delete all these korea words?

**Comment by Qiyangcao** [comment]
@JarvisLee0423  
1. git checkout **A** represents your project should be based on the version **A** now, so you need to build all the library based on  **A**, I assumed your pytorch lib is still based on the master version, since you turn to **A** branch after building them on master branch.  

2. Yes, the korean words may be the problems ,I already provided you the modified code

**Comment by JarvisLee0423** [comment]
@Qiyangcao Yeah, I have already changed those words into your code, but it didn't work...... and I didn't find the version A, its just have 'develop', gas-micro, 'gh-pages' and 'targeting' branches...and I still dond't know what's your mean...

**Comment by Qiyangcao** [comment]
@JarvisLee0423  Did u really try the command "**git checkout f67963b**" in your terminal ...

**Comment by Qiyangcao** [comment]
@JarvisLee0423 btw... i said  I missed a lot of details, I'm sorry I can't help more....

**Comment by JarvisLee0423** [comment]
@Qiyangcao Oh, I am sorry, I don't know you mean in the terminal...Never mind, I just want to solve this problem...

**Comment by Qiyangcao** [comment]
@JarvisLee0423  A small recommendation , if you wanna know the structure of his project, you can turn to this link [https://torchcraft.github.io/TorchCraftAI/docs/bptut-intro.html]. Most of his work is rule-based, the network part is clearly introduced through the link. If u wanna develop your agent to compete, maybe the well-known Locutus is a better material to learn, since more open sourced projects are built up on this agent.

**Comment by JarvisLee0423** [comment]
I have already done with this problem.
The solution is that you when you build the cherrypi and meet this problem, please open the build folder in the root directory of TorchCraftAI. Then you will find a file named CmakeCache.txt.
Then you just need to find the variables related to the GFLAGS and GLOG then modify their values with the exactly correct derectory maunally and save the file, then build the cherrypi again, you will never meet this problem again.
The last thing you have to pay attention to, which is that after you having done all of the things above, if you still build cherrypi failure. You can follow the instructions in https://github.com/TorchCraft/TorchCraftAI/issues/12#issuecomment-575876262
, then you will successfully build the cherrypi.

**Comment by leonfg** [comment]
> 
> 
> I have already done with this problem.
> The solution is that you when you build the cherrypi and meet this problem, please open the build folder in the root directory of TorchCraftAI. Then you will find a file named CmakeCache.txt.
> Then you just need to find the variables related to the GFLAGS and GLOG then modify their values with the exactly correct derectory maunally and save the file, then build the cherrypi again, you will never meet this problem again.
> The last thing you have to pay attention to, which is that after you having done all of the things above, if you still build cherrypi failure. You can follow the instructions in [#12 (comment)](https://github.com/TorchCraft/TorchCraftAI/issues/12#issuecomment-575876262)
> , then you will successfully build the cherrypi.

Thanks!

**Comment by jgehring** [comment]
I'm closing this now since @JarvisLee0423 described a manual workaround (editing CMakeCache.txt and inserting the correct paths to the compiled gflags and glog libraries).
