### ISSUE TITLE
3rdparty/Ale is not an existing directory

### ISSUE THREAD

**Issue by MicroDK** [TorchCraft/TorchCraftAI#15]
Following the guide at https://torchcraft.github.io/TorchCraftAI/docs/install-macos.html, doing the cmake of TorchCraftAI and CherryPi:

cmake .. -DCMAKE_BUILD_TYPE=relwithdebinfo

You get the following errror:

CMake Error at CMakeLists.txt:72 (ADD_SUBDIRECTORY):
  ADD_SUBDIRECTORY given source
  "[path-to-TorchCraft]/TorchCraftAI/3rdparty/ale" which is not an existing
  directory.

CMake Error at CMakeLists.txt:73 (SET_TARGET_PROPERTIES):
  SET_TARGET_PROPERTIES Can not find target to add properties to: ale-lib

CMake Error at CMakeLists.txt:74 (TARGET_INCLUDE_DIRECTORIES):
  Cannot specify include directories for target "ale-lib" which is not built
  by this project.

Is it a bug that the Ale directory is not present? Or is it a bug that the lines 72, 73 and 74  TorchCraftAI/CMakeLists.txt are there?

Commeting out lines 72, 73 and 74 in TorchCraftAI/CMakeLists.txt resolves the issue.

**Comment by danthe3rd** [comment]
Hi @MicroDK 

I updated the master branch with the `ale` directory which should fix your error.

Thank you for reporting!

**Comment by jgehring** [comment]
Closing this as resolved, please feel free to re-open if you're still running into issues because of this @MicroDK.
