### ISSUE TITLE
[Linux] PyTorch build ERROR on release-1.1

### ISSUE THREAD

**Issue by ianchen28** [TorchCraft/TorchCraftAI#17]
on Linux, got the following error when building pytorch according to the installation instruction:

>  error: ‘float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)’ is deprecated [-Werror=deprecated-declarations]
weights(i, d, p) = cblas_sgemm_alloc(CblasAMatrix, m_p, n, k_p);
^

at the step
```
pushd 3rdparty/pytorch/tools/
REL_WITH_DEB_INFO=1 python build_libtorch.py
popd
```

whole error log:
> [ 22%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/util/type_resolver_util.cc.o
[ 22%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/wire_format.cc.o
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp: In member function ‘void mkldnn::impl::cpu::_ref_rnn_common_t<aprop>::pack_weights(int, int, int, int, int, int, int, float**, int, int*, const float*, float*, bool)’:
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:891:36: error: ‘float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)’ is deprecated [-Werror=deprecated-declarations]
                 weights(i, d, p) = cblas_sgemm_alloc(CblasAMatrix, m_p, n, k_p);
                                    ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:791:25: note: declared here
 MKL_DEPRECATED_C float* cblas_sgemm_alloc(const  CBLAS_IDENTIFIER identifier,
                         ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:891:36: error: ‘float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)’ is deprecated [-Werror=deprecated-declarations]
                 weights(i, d, p) = cblas_sgemm_alloc(CblasAMatrix, m_p, n, k_p);
                                    ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:791:25: note: declared here
 MKL_DEPRECATED_C float* cblas_sgemm_alloc(const  CBLAS_IDENTIFIER identifier,
                         ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp: In member function ‘void mkldnn::impl::cpu::_ref_rnn_common_t<aprop>::free_packed_weights(int, int, int, float**)’:
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:979:17: error: ‘void cblas_sgemm_free(float*)’ is deprecated [-Werror=deprecated-declarations]
                 cblas_sgemm_free(weights(i, j, k));
                 ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:804:23: note: declared here
 MKL_DEPRECATED_C void cblas_sgemm_free(float *dest);
                       ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:979:17: error: ‘void cblas_sgemm_free(float*)’ is deprecated [-Werror=deprecated-declarations]
                 cblas_sgemm_free(weights(i, j, k));
                 ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:804:23: note: declared here
 MKL_DEPRECATED_C void cblas_sgemm_free(float *dest);
                       ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp: In instantiation of ‘void mkldnn::impl::cpu::_ref_rnn_common_t<aprop>::pack_weights(int, int, int, int, int, int, int, float**, int, int*, const float*, float*, bool) [with mkldnn_prop_kind_t aprop = (mkldnn_prop_kind_t)64u]’:
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:1183:17:   required from here
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:891:53: error: ‘float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)’ is deprecated [-Werror=deprecated-declarations]
                 weights(i, d, p) = cblas_sgemm_alloc(CblasAMatrix, m_p, n, k_p);
                                                     ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:791:25: note: declared here
 MKL_DEPRECATED_C float* cblas_sgemm_alloc(const  CBLAS_IDENTIFIER identifier,
                         ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:891:53: error: ‘float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)’ is deprecated [-Werror=deprecated-declarations]
                 weights(i, d, p) = cblas_sgemm_alloc(CblasAMatrix, m_p, n, k_p);
                                                     ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:791:25: note: declared here
 MKL_DEPRECATED_C float* cblas_sgemm_alloc(const  CBLAS_IDENTIFIER identifier,
                         ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:891:53: error: ‘float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)’ is deprecated [-Werror=deprecated-declarations]
                 weights(i, d, p) = cblas_sgemm_alloc(CblasAMatrix, m_p, n, k_p);
                                                     ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:791:25: note: declared here
 MKL_DEPRECATED_C float* cblas_sgemm_alloc(const  CBLAS_IDENTIFIER identifier,
                         ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp: In instantiation of ‘void mkldnn::impl::cpu::_ref_rnn_common_t<aprop>::free_packed_weights(int, int, int, float**) [with mkldnn_prop_kind_t aprop = (mkldnn_prop_kind_t)64u]’:
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:1183:17:   required from here
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:979:33: error: ‘void cblas_sgemm_free(float*)’ is deprecated [-Werror=deprecated-declarations]
                 cblas_sgemm_free(weights(i, j, k));
                                 ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:804:23: note: declared here
 MKL_DEPRECATED_C void cblas_sgemm_free(float *dest);
                       ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:979:33: error: ‘void cblas_sgemm_free(float*)’ is deprecated [-Werror=deprecated-declarations]
                 cblas_sgemm_free(weights(i, j, k));
                                 ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:804:23: note: declared here
 MKL_DEPRECATED_C void cblas_sgemm_free(float *dest);
                       ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:979:33: error: ‘void cblas_sgemm_free(float*)’ is deprecated [-Werror=deprecated-declarations]
                 cblas_sgemm_free(weights(i, j, k));
                                 ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:804:23: note: declared here
 MKL_DEPRECATED_C void cblas_sgemm_free(float *dest);
                       ^
[ 22%] Building CXX object third_party/protobuf/cmake/CMakeFiles/libprotobuf.dir/__/src/google/protobuf/wrappers.pb.cc.o
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp: In instantiation of ‘void mkldnn::impl::cpu::_ref_rnn_common_t<aprop>::pack_weights(int, int, int, int, int, int, int, float**, int, int*, const float*, float*, bool) [with mkldnn_prop_kind_t aprop = (mkldnn_prop_kind_t)128u]’:
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:1184:17:   required from here
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:891:53: error: ‘float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)’ is deprecated [-Werror=deprecated-declarations]
                 weights(i, d, p) = cblas_sgemm_alloc(CblasAMatrix, m_p, n, k_p);
                                                     ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:791:25: note: declared here
 MKL_DEPRECATED_C float* cblas_sgemm_alloc(const  CBLAS_IDENTIFIER identifier,
                         ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:891:53: error: ‘float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)’ is deprecated [-Werror=deprecated-declarations]
                 weights(i, d, p) = cblas_sgemm_alloc(CblasAMatrix, m_p, n, k_p);
                                                     ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:791:25: note: declared here
 MKL_DEPRECATED_C float* cblas_sgemm_alloc(const  CBLAS_IDENTIFIER identifier,
                         ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:891:53: error: ‘float* cblas_sgemm_alloc(CBLAS_IDENTIFIER, int, int, int)’ is deprecated [-Werror=deprecated-declarations]
                 weights(i, d, p) = cblas_sgemm_alloc(CblasAMatrix, m_p, n, k_p);
                                                     ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:791:25: note: declared here
 MKL_DEPRECATED_C float* cblas_sgemm_alloc(const  CBLAS_IDENTIFIER identifier,
                         ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp: In instantiation of ‘void mkldnn::impl::cpu::_ref_rnn_common_t<aprop>::free_packed_weights(int, int, int, float**) [with mkldnn_prop_kind_t aprop = (mkldnn_prop_kind_t)128u]’:
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:1184:17:   required from here
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:979:33: error: ‘void cblas_sgemm_free(float*)’ is deprecated [-Werror=deprecated-declarations]
                 cblas_sgemm_free(weights(i, j, k));
                                 ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:804:23: note: declared here
 MKL_DEPRECATED_C void cblas_sgemm_free(float *dest);
                       ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:979:33: error: ‘void cblas_sgemm_free(float*)’ is deprecated [-Werror=deprecated-declarations]
                 cblas_sgemm_free(weights(i, j, k));
                                 ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:804:23: note: declared here
 MKL_DEPRECATED_C void cblas_sgemm_free(float *dest);
                       ^
/home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:979:33: error: ‘void cblas_sgemm_free(float*)’ is deprecated [-Werror=deprecated-declarations]
                 cblas_sgemm_free(weights(i, j, k));
                                 ^
In file included from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/gemm/os_blas.hpp:39:0,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.hpp:30,
                 from /home/chenyuyang01/git/TorchCraftAI/3rdparty/pytorch/third_party/ideep/mkl-dnn/src/cpu/ref_rnn.cpp:39:
/home/chenyuyang01/anaconda3/envs/sc2/include/mkl_cblas.h:804:23: note: declared here
 MKL_DEPRECATED_C void cblas_sgemm_free(float *dest);
                       ^
Scanning dependencies of target c10_StreamGuard_test
[ 22%] Building CXX object c10/test/CMakeFiles/c10_StreamGuard_test.dir/core/StreamGuard_test.cpp.o
Scanning dependencies of target c10_DeviceGuard_test
[ 22%] Building CXX object c10/test/CMakeFiles/c10_DeviceGuard_test.dir/core/DeviceGuard_test.cpp.o
Scanning dependencies of target c10_TensorTypeId_test
[ 23%] Building CXX object c10/test/CMakeFiles/c10_TensorTypeId_test.dir/core/TensorTypeId_test.cpp.o
Scanning dependencies of target c10_registry_test
[ 23%] Linking CXX executable ../../bin/c10_InlineDeviceGuard_test
[ 23%] Building CXX object c10/test/CMakeFiles/c10_registry_test.dir/util/registry_test.cpp.o

**Comment by danthe3rd** [comment]
Hello, and thank you for reporting this bug

It looks like this bug might be related to having an outdated version of PyTorch on our end - but until we get that sorted out (@ebetica ?), maybe it's easier for you to downgrade MKL version if possible.
Reference: https://github.com/pytorch/pytorch/issues/18365

**Comment by ianchen28** [comment]
> Hello, and thank you for reporting this bug
> 
> It looks like this bug might be related to having an outdated version of PyTorch on our end - but until we get that sorted out (@ebetica ?), maybe it's easier for you to downgrade MKL version if possible.
> Reference: [pytorch/pytorch#18365](https://github.com/pytorch/pytorch/issues/18365)

Downgrade works to the version 2019.1, thanks : D

BTW, got another error when building cherrypi, would you plase have a look? https://github.com/TorchCraft/TorchCraftAI/issues/18#issue-471464696
