### ISSUE TITLE
TorchCraftAI failed to build

### ISSUE THREAD

**Issue by bwangll** [TorchCraft/TorchCraftAI#3]
I follow the official website tutorial at this step: python setup.py build
I don't know about this setup. The py file is build, I hope the tutorial can be more detailed, because I am a beginner, thank you

**Comment by koalarun** [comment]
go to the directory "TorchCraftAI\3rdparty\pytorch", and run the command "python setup.py build"

**Comment by bwangll** [comment]
> 转到目录“TorchCraftAI \ 3rdparty \ pytorch”，然后运行命令“python setup.py build”

In the process of execution, I encountered a compilation error of the source code. I don't know what caused this.

**Comment by bwangll** [comment]
> 转到目录“TorchCraftAI \ 3rdparty \ pytorch”，然后运行命令“python setup.py build”

Do I need to put the "TorchCraftAI" file and love in the "$Starcarft" directory?

**Comment by bwangll** [comment]
> > 转到目录“TorchCraftAI \ 3rdparty \ pytorch”，然后运行命令“python setup.py build”
![image](https://user-images.githubusercontent.com/38982792/49575386-8c027680-f97d-11e8-9f73-1284d53072b0.png)

**Comment by koalarun** [comment]
@CNGU-wang this is just warning, you can ignore them.

**Comment by CNGU-wang** [comment]
> @ CNGU-wang这只是警告，你可以忽略它们
.Failed to run' tool sbui1d pytorch_ 1ibs. bat --use-fbgemn --use-mnpack . use-mkldnn -use-qnpack caffe2
But I received this error
