### ISSUE TITLE
How to run Tutorial cases

### ISSUE THREAD

**Issue by ianchen28** [TorchCraft/TorchCraftAI#7]
Hi there,

I have successfully built and run the cherrypi on windows.

Now I am trying to follow the tutorial about building placement and micro management.
After going through the tutorial blog I found there is no executable files in the ./build folder according to
https://torchcraft.github.io/TorchCraftAI/docs/bptut-rl.html
eg. ./build/tutorials/building-placer/bp-train-rl

Should there be any modification about the building procedure according to the 'Installation(Windows)' part of TorchCraftAI (https://torchcraft.github.io/TorchCraftAI/docs/install-windows.html)?

Thanks in advance : )

**Comment by ebetica** [comment]
Sorry, we do not support training on Windows. Please use a Linux VM

**Comment by ianchen28** [comment]
Ok I see, thank you
