### ISSUE TITLE
Link error while building Cherrypi in both Windows and Linux OS

### ISSUE THREAD

**Issue by ianchen28** [TorchCraft/TorchCraftAI#8]
Hi there,

I tried to build cherrypi on Windows and Linux and encountered the same link error of "multiple definition" of some functions and found out that it might be caused by the duplicated cpp/h files in `src/` directory and the `src/gameutils/` directory, such as the `botscenario.cpp`.

The building procedure can succeed when I removed the redundant files from `src/`.

Would you please have a look at the case if it is an intended duplication or a careless mistake?

Thank you in advance.

**Comment by ebetica** [comment]
Hi, this is a mistaken, we'll fix it, thanks for bringing it to our attention!
